[workspace]
resolver = "2"

members = [
    "packages/*",
]

[workspace.package]
version = "0.1.0"
edition = '2021'
authors = ["José Miguel Sarasola <alosarjos@gmail.com>"]
description = "Backend server for BackLogger project"