[package]
name = "backlogger_server"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "backlogger_server"

[dependencies]
axum = "0.7.0"
hyper = "1.0"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
reqwest = "0.11.20"
